### ISSUE TITLE
extract parameters(mgc,lf0,bap) from wav files

### ISSUE THREAD

**Issue by pineking** [MattShannon/HTS-demo_CMU-ARCTIC-SLT-STRAIGHT-AR-decision-tree#2]
Is there a script file which can extract mgc/lf0/bap files from wav file?
I can not find it in the scripts directory.

**Comment by MattShannon** [comment]
Hi pineking,

Just running "make" as specified in INSTALL should suffice.

The commands to convert wav to straight parameters and then straight
parameters to mgc, lf0 and bap parameters are in data/Makefile.in.  I
agree it would be nice to have a separate command to run the
extraction, but this repository is based on the HTS demo for
simplicity, and the HTS demo does things this way.

**Comment by pineking** [comment]
Thanks, Matt.

I will try it.

Qingsong

On Mon, Jan 5, 2015 at 2:57 PM, Matt Shannon notifications@github.com
wrote:

> Hi pineking,
> 
> Just running "make" as specified in INSTALL should suffice.
> 
> The commands to convert wav to straight parameters and then straight
> parameters to mgc, lf0 and bap parameters are in data/Makefile.in. I
> agree it would be nice to have a separate command to run the
> extraction, but this repository is based on the HTS demo for
> simplicity, and the HTS demo does things this way.
> 
> On Sun, 04 Jan 2015 04:08:45 -0800
> pineking notifications@github.com wrote:
> 
> > Is there a script file which can extract mgc/lf0/bap files from wav
> > file? I can not find it in the scripts directory.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/MattShannon/HTS-demo_CMU-ARCTIC-SLT-STRAIGHT-AR-decision-tree/issues/2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MattShannon/HTS-demo_CMU-ARCTIC-SLT-STRAIGHT-AR-decision-tree/issues/2#issuecomment-68674273
> .

## 

---

Qingsong Liu
liuqs.ustc@gmail.com

## Univ. of Sci.& Tech. of China
